- lib/bn.js
- test/arithmetic-test.js
- test/red-test.js
Make `.sign` a plain integer instead of boolean. Possible values are
either `0` or `1`.
Other improvements:
- Peel first iteration of `smallMulTo`. This gives about 5% boost to
multiplication
- Cast array loads to small integers, this gives about 5% boost to
addition and probably other routines too
cc @calvinmetcalf This is probably going to be a major version bump. What are your thoughts on this?
> bn: `.sign` either `0` or `1`, other improvements

- README.md
Fix documentation since function is actually static for BN class.
> Correct doc for `BN#isBN()`

- lib/bn.js
Alternative to having a run-time check?
Error is more legible too,  IMHO.
The existing error:
``` js
if (!val) throw new Error(msg || 'Assertion failed');
^
Error: Assertion failed
```
The new 
``` js
TypeError: mynum.toBuffer is not a function
```
> only define toBuffer if Buffer is defined

- lib/bn.js
- test/constructor-test.js
> 10% performance drop, but 200% better debuggability.
Hopefully this resolves that problem @indutny
> check unexpected high bits for invalid characters

- lib/bn.js
- test/red-test.js
> bn: fix Red#imod

- test/constructor-test.js
- test/pummel/dh-group-test.js
- test/red-test.js
`new Buffer` -> `Buffer.from` or `Buffer.alloc`.
We should not use Buffer constructor which is deprecated and unsafe.
The behavior of new Buffer() is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or Buffer initialization is not performed.
To make the creation of Buffer instances more reliable and less error-prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.
Check this out: 
* https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
This PR failed CI test on Node.js `0.10`, `0.12`. However, those versions are no longer …
> new Buffer is deprecated and unsafe

- lib/bn.js
- test/arithmetic-test.js
Issue #215 
When we sub number from BN instance and this number equal to number in
BN instance we receive zero with negative sign.
> fix iaddn sign issue

- lib/bn.js
Remove extra bitwise operator
performance:
```js
function toBitArray1 (num) {
var w = new Array(num.bitLength());
for (var bit = 0; bit < w.length; bit++) {
var off = (bit / 26) | 0;
var wbit = bit % 26;
w[bit] = (num.words[off] >>> wbit) & 0x01;
// w[bit] = (num.words[off] & (1 << wbit)) >>> wbit;
}
return w;
}
function toBitArray2 (num) {
var w = new Array(num.bitLength());
for (var bit = 0; bit < w.length; bit++) {
var off = (bit / 26) | 0;
var wbit = bit % 26;
// w[bit] = (num.words[off] >>> wbit) & 0x01;
w[bit] = (num.words[off] & (1 << wbit)) >>> wbit;
}
return w;
}
const z = new BN(require('crypto').randomBytes(32))
console.time('toBitArray1')
for (let i = 0; i < 1e5; ++i) toBitArray1(z)
console.timeEnd('toBitArray1')
console.time('toBitArray2')
for (let i = 0; i < 1e5; ++i) …
```
> optimize toBitArray function

- lib/bn.js
Currently there no solution for #211 
Result should be correct even if code is slow, `jumboMulTo` will be temporary disabled. It can be enabled back when code will be fixed.
> Temporary disable jumboMulTo in BN#mulTo

- benchmarks/index.js
- lib/bn.js
- test/utils-test.js
From 6x to 174x improvement. Was need turn off bignum, because node 12 not supported.
```bash
$ # old 768 bytes number
$ SEED=27af4987aa60091dc42b1314d340e8c0 node index.js toArray
Seed: 27af4987aa60091dc42b1314d340e8c0
Benchmarking: toArray
bn.js#toArray x 3,437 ops/sec ±7.94% (7 runs sampled)
------------------------
Fastest is bn.js#toArray
========================
$ # old 32 bytes number
$ SEED=27af4987aa60091dc42b1314d340e8c0 node index.js toArray
Seed: 27af4987aa60091dc42b1314d340e8c0
Benchmarking: toArray
bn.js#toArray x 947,728 ops/sec ±3.40% (9 runs sampled)
------------------------
Fastest is bn.js#toArray
========================
$ # new 768 bytes number
$ SEED=27af4987aa60091dc42b1314d340e8c0 node index.js toArray
Seed: 27af4987aa60091dc42b1314d340e8c0
Benchmarking: toArray …
```
> Improve performance of toArrayLike

- benchmarks/index.js
- package.json
- yarn.lock
@mathiasbynens can you share benchmark which was used in article? https://v8.dev/features/bigint#use-cases
`bn.js` VS `BigInt`
```bash
$ node --version
v12.8.0
$ uname -r
5.1.20-300.fc30.x86_64
$ grep 'model name' -m 1 /proc/cpuinfo
model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
```
```bash
$ SEED=d3010f0048b13a628169fc81a4c0318d node index.js 
Load bignum error: Cannot find module 'bignum'
Seed: d3010f0048b13a628169fc81a4c0318d
Benchmarking: create-10
bn.js#create-10 x 962,231 ops/sec ±1.13% (9 runs sampled)
BigInt#create-10 x 2,684,467 ops/sec ±0.72% (9 runs sampled)
------------------------
Fastest is BigInt#create-10
========================
Benchmarking: toString-10
bn.js#toString-10 x 466,028 ops/sec ±0.94% (9 runs sampled)
BigInt#toString-10 x 691,462 ops/sec ±0.41% (7 runs …
```
> Benchmark for BigInt

- CHANGELOG.md
- package.json
- Temporary workaround for BN#_move (#236)
- Add eslintrc instead config in package.json (#237)
> Release: 5.1.1

- lib/bn.js
Fixes #239 on the 5.x branch
Made sure that the respective code part is actually touched by the unit tests.
(second try following #247 after CI problems)
> Fix BN v5/v4 interoperability issue for v5.x

- lib/bn.js
`Symbol.for` is defined but not implemented in NGINX njs plugin and throws exception.
> err InternalError: not implemented
>     at Symbol.for (native)
> 
http://hg.nginx.org/njs/file/default/src/njs_symbol.c#l174
Suggestion for https://github.com/indutny/bn.js/blob/5707aed66c02ae10f8c7d59f5244fcce1c24cdb6/lib/bn.js#L373
Wrap in try/catch block and revert to `BN.prototype.inspect = inspect;` on error.
> Add support for defined but not implemented Symbol.for

- lib/bn.js
- test/constructor-test.js
Close #208 
~WIP... need to fix other bases too.~ question: how we should interpret little-endian for other bases?
> Fix LE constructor for HEX

- .github/workflows/ci.yaml
Some deps require a higher node version that we test in CI: https://github.com/indutny/bn.js/runs/1962262706
> Remove node matrix from CI

- lib/bn.js
Closes issue #259
Redeclaring Buffer prohibits using a globally-defined polyfill.
> fix: Buffer not using global in browser, closes #259

- CHANGELOG.md
- package.json
- fix: Buffer not using global in browser (#260)
- Fix LE constructor for HEX (#265)
> New release: 5.2.0

- lib/bn.js
- test/utils-test.js
In some circumstances the hex encoding of big numbers is wrong. In addition to a display issue, given that the the hex string if often used as an intermediate representation in transport/conversion scenarios, the re-constructed big number can actually change its value, creating serious issues.
> Fix serious issue in `.toString(16)`

- README.md
> Document `length` unit in `toBuffer(...)` input

- README.md
As mentioned here https://github.com/indutny/bn.js/issues/306 max plain JS number argument value seems to undocumented. I've added info in README.md.
> Document the max plain JS number argument value

- lib/bn.js
- test/utils-test.js
This backports #295 to `v4.x` branch
4.x usage is still at ~75%
E.g. `elliptic` uses 4.x
Original description:
```
* Add test for `.toString(16)`
* Fix serious issue in `.toString(16)`
The hex encoding of some numbers is wrong. Since the string representation is also used for interoperability between BigInt libraries, this bug is causing a number modification when a BN.js number is converted into another BigInt class, for example the BigNumber of ethers.js.
```
> backport(4.x): Fix serious issue in `.toString(16)` (#295)
